theme: jekyll-theme-primer
markdown: kramdown

# Set the source directory for Jekyll
source: /root

# SASS configuration
sass:
  sass_dir: assets/css
  style: compressed

# Exclude the following files from the build
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - node_modules
  - vendor

# Plugins used by GitHub Pages
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-gist
  - jekyll-github-metadata
  - jekyll-optional-front-matter
  - jekyll-readme-index
  - jekyll-relative-links
  - jekyll-default-layout
  - jekyll-titles-from-headings

# Pagination settings
paginate: 5
paginate_path: "/page:num/"

# Metadata for SEO
title: "SCHED Project"
description: "A project for viewing and interacting with site locations in Redland City, QLD."
author: "tresseisjoel52"
url: "https://tresseisjoel52.github.io/SCHED"
